import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import AuthProvider from "./auth/Provider";
import NavBar from "./NavBar";
import { ChatLogProvider } from "./context/ChatLog";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ChatLogProvider>
          <body>
            <NavBar />
            {children}
          </body>
        </ChatLogProvider>
      </AuthProvider>
    </html>
  );
}
